markdown: kramdown
kramdown:
  input: GFM
  use_coderay: true

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class
pygments: true
permalink: /:title
gems:
  - jekyll-mentions
